lec2+lec4
IlyaOrlov/PythonCourse pull request #264
Opened 2020-08-13 17:52 UTC by Rusbrus

2020-08-13 20:52 UTC, IlyaOrlov commented on Practice/aulov_r/4lec2.py
> +a = str(num)
num и так является строкой, можно работать сразу с ним, без a

2020-08-13 20:54 UTC, IlyaOrlov commented on Practice/aulov_r/4lec4.py
> +a = open("file1.txt")
Зачем два раза открывать файл?

2020-08-13 20:56 UTC, IlyaOrlov commented on Practice/aulov_r/4lec5.py
> +    a = a.replace(i, (b[i]))
Скобки вокруг b лишние. Чем меньше лишних символов - тем чище код.

2020-08-14 14:52 UTC, Rusbrus commented on Practice/aulov_r/4lec4.py
> +a = open("file1.txt")
Да здесь не надо a = open("file1.txt") ошибся

2020-08-14 14:53 UTC, Rusbrus commented on Practice/aulov_r/4lec5.py
> +    a = a.replace(i, (b[i]))
понял приму к сведению

2020-08-18 18:08 UTC, IlyaOrlov requested changes

2020-08-18 18:08 UTC, IlyaOrlov commented on Practice/aulov_r/4lec3.py
> +arr.sort()
Разумно) Но все-таки надо свою функцию сортировки написать. И именно методом выбора.

2020-08-20 13:55 UTC, IlyaOrlov approved these changes

2020-08-20 13:56 UTC, merged