Lab2 + Lab3 + Lab4
IlyaOrlov/PythonCourse pull request #267
Opened 2020-08-18 15:08 UTC by MikhailTreushnikov

2020-08-18 17:46 UTC, IlyaOrlov commented
Файлы .DS_Store и Practice/.DS_Store не должны попасть на master. Нужно их удалить (предварительно можно скопировать в какую-нибудь резервную папку), сделать commit, push. Потом их можно вернуть локально и добавить в gitignore

2020-08-18 18:55 UTC, IlyaOrlov requested changes

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/2.3.py
> +Object1.speed = Object1.list[0].use(Object1.speed)
Мы изменяем атрибут экземпляра извне, используя атрибут этого же экземпляра. Это как в автоматическом пистолете патрон из обоймы в патронник руками перекладывать. Выглядит как нарушение инкапсуляции. Пользователь класса standart_Charachter должен знать, что такое list (кстати нехорошо использовать ключевые слова языка в качестве имен переменных), что у него есть 0-й элемент (если он есть), у которого есть метод use....

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/2.3.py
> +class LootUp:
Вопрос для размышления: если создать класс (иерархию классов) действий (с анимацией бега, полета, плавания) так, что при нахождении очередного предмета, некое базовое действие персонажа будет заменяться на экземпляр этого класса (Object1.running = ActionRunning(), Object1.running = ActionRunJumping(), Object1.running = ActionFlying()), что бы это дало, и как это можно реализовать?

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/3.2.py
> +    List = []
А если просто преобразовать **a** к типу строка?

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/3.3.py
> +def sort (arr,length):
Хорошо. Только это пузырьковый метод сортировки, а не метод выбора, указанный в задании.

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/3.3.py
> +    while j<length-1:
Чтоб сократить количество итераций при пузырьковой сортировке условием выхода из внешнего цикла должно служить отсутствие перестановок во внутреннем цикле. Так будет быстрее.

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/3.3.py
> +                tmp = arr[i+1]
Удобней так: arr[i+1], arr[i] = arr[i], arr[i+1]

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/4.1.py
> +def change (source):
Замену табуляции на пробелы тоже стоит предусмотреть.

2020-08-18 18:55 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/4.2.py
> +str = "Hello my frien. What is your name."
Не стоит использовать имена встроенных типов str, dict (и любые другие ключевые слова Python) для именования переменных. PyCharm обычно подсвечивает такие ошибки.

2020-08-25 10:56 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/2.3.py
> +Object1.speed = Object1.list[0].use(Object1.speed)
Что мог поправил но есть вопросы по этой части, так как не совсем представляю как это реализовать

2020-08-25 10:56 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/3.2.py
> +    List = []
Переделал с помощью среза

2020-08-25 10:57 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/3.3.py
> +def sort (arr,length):
Сделал сортировку выбором

2020-08-25 10:57 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/4.1.py
> +def change (source):
Исправил

2020-08-25 10:57 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/4.2.py
> +str = "Hello my frien. What is your name."
Исправил

2020-08-25 15:54 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/3.2.py
> +    List = []
Да можно и без среза. Главное, чтоб выводились не только цифры, но и их индексы:
1 цифра равна 1
2 цифра равна 0
3 цифра равна 8
4 цифра равна 9
5 цифра равна 4

2020-08-25 16:10 UTC, IlyaOrlov requested changes

2020-08-25 16:10 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/WrapStrToFile.py
> +            print("File doesn't exist yet")
Вопрос на понимание. Геттер по своему смыслу всегда должен что-то возвращать. Что же он возвращает здесь, в случае исключения?

2020-08-25 16:10 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/pupil.py
> +        super(Pupil, self).solve_task()
Здесь тоже можно было написать просто super()

2020-08-25 16:10 UTC, IlyaOrlov commented on .gitignore
> +.DS_Store
Сам .gitignore тоже стоит добавить в .gitignore

2020-08-27 15:55 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/WrapStrToFile.py
> +            print("File doesn't exist yet")
Должен возвращать  None

2020-08-27 19:16 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/WrapStrToFile.py
> +            print("File doesn't exist yet")
OK. Но лучше всегда возвращать None явно (тем более, если в функции уже есть явный return), иначе это выглядит, как будто забыли предусмотреть этот случай.

2020-09-08 17:27 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/3.2.py
> +    List = []
Поправил

2020-09-09 11:24 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/3.2.py
> +    List = []
ОК, только нумерацию надо с единицы начать. В enumerate для это можно передать отдельный аргумент.

2020-09-09 11:26 UTC, IlyaOrlov reviewed
Ожидается исправление оставшихся замечаний. Или хотя бы ответ на них.

2020-10-19 11:07 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/pupil.py
> +        super(Pupil, self).solve_task()
поправил

2020-10-19 11:07 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/WrapStrToFile.py
> +            print("File doesn't exist yet")
поправил

2020-10-19 11:07 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/3.2.py
> +    List = []
поправил

2020-10-19 11:08 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/2.3.py
> +class LootUp:
Прошу прощения за отсутсвие обратной связи на в такой длительный момент времени. Исправил вроде все.

2020-10-19 18:19 UTC, IlyaOrlov approved these changes

2020-10-19 18:19 UTC, merged