Tasks from Lection 2, Lection 4, Lection 5
IlyaOrlov/PythonCourse pull request #269
Opened 2020-08-19 13:10 UTC by SemKilyaev

2020-08-19 15:25 UTC, IlyaOrlov requested changes

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_2_Task_2.py
> +        print(f"{a} equal {b}")
А что вернет функция в этой ветке?

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_2_Task_3.py
> +        thing.run = thing.runSlow
Не понятно, зачем нужны сразу два атрибута run и action. По возможности, приведите пример их использования.

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_4_Task_1.py
> +        if i % 3 == 0:
Лучше сначала проверить i % 15, а потом уже и i % 5 и i % 3. Получится меньше проверок и меньше кода.

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_4_Task_4.py
> +        result = re.sub(' +', '\t', string)
"+" - это чтоб результат замены был виден?

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_4_Task_6.py
> +        if index is not None:
Если искомое число встречается в нескольких столбцах - должны быть удалены все эти столбцы.

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_5_Task_2.py
> +class Man(object):
Можно было просто импортировать Man из Lection_5_Task_1.py

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_5_Task_3.py
> +            print("File not found")
Вопрос на понимание: что вернет геттер в случае исключения?

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/pep8task.py
> +           #os.rename(path + '/' + mp3), path + '/' + hashname))   Лишняя скобка в середине
И не только в середине.

2020-08-19 15:25 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/pep8task.py
> +          #f = open(output, 'r')   Лишние отступы
Вопрос к размышлению: чем удаление лишних отступов здесь лучше, чем добавление отступов?

2020-08-19 15:54 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_4_Task_4.py
> +        result = re.sub(' +', '\t', string)
Вхождение одного или больше пробелов, я с этой целью сделал

2020-08-19 15:57 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_5_Task_3.py
> +            print("File not found")
Уже понял ошибку, если нет return, то он возвращает еще и None после print, не придал в начале этому значение, исправлю на return "File not found"

2020-08-19 16:04 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_2_Task_2.py
> +        print(f"{a} equal {b}")
Если а больше, чем b, то вернет а, если b>a, то вернет b в задании нужно было вывести большое число на экран

2020-08-19 16:14 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/pep8task.py
> +          #f = open(output, 'r')   Лишние отступы
Я могу только предположить, что открывать файл на чтение на каждой итерации цикла, это не очень хорошо, лучше открыть на чтение один раз после цикла... Я просто еще ни видел код, где в цикле открывают файл на чтение, а не на дозапись

2020-08-19 16:24 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_2_Task_2.py
> +        print(f"{a} equal {b}")
Так а что вернет функция, если b == a?

2020-08-19 16:28 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_4_Task_4.py
> +        result = re.sub(' +', '\t', string)
Точно, это ж регулярка) Но нужно заменять строго 4 пробела на один символ табуляции. Используйте {4}

2020-08-19 16:31 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/pep8task.py
> +          #f = open(output, 'r')   Лишние отступы
Да, все правильно.

2020-08-19 16:31 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_2_Task_2.py
> +        print(f"{a} equal {b}")
Что число b равно а, или вы имеете ввиду, что это лишнее условие?

2020-08-19 16:32 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_4_Task_4.py
> +        result = re.sub(' +', '\t', string)
Хорошо, исправлю)

2020-08-19 16:39 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_2_Task_2.py
> +        print(f"{a} equal {b}")
Суть вопроса та же, что и в Lection_5_Task_3.py: если везде есть return, а здесь - нет, то велика вероятность, что этот момент просто не учли (помните Дзен Питона: "явное лучше, чем неявное"). 
Можно либо убрать условие, либо явно вернуть None.

2020-08-19 16:49 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_2_Task_2.py
> +        print(f"{a} equal {b}")
Ааааа, понял, тогда лучше верну None

2020-08-19 17:55 UTC, IlyaOrlov requested changes

2020-08-19 17:55 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_4_Task_6.py
> +def delete_column(matrix, num_delete):
А если у нас искомое число повторится в одном ряду дважды? Например, arr = [[1, 2, 2], [3, 4, 5]]
Удаляем 2. По идее, должен остаться только 1-й столбец.

2020-08-20 17:58 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_4_Task_6.py
> +    find_num_for_delete(matrix, num_delete)
Хорошо, но не эффективно, т.к. на каждом уровне рекурсии вы полностью обходите матрицу в find_num_for_delete независимо от результата поиска.

2020-10-01 19:57 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_6_Task_3.py
> +        self.start_time = time.clock()
OK, но чтоб засечь время лучше использовать time.perf_counter или time.process_time или time.time

2020-10-01 20:02 UTC, IlyaOrlov approved these changes

2020-10-01 20:03 UTC, merged