Iterator, generator are done, lec4, lec5, lec6, lec7, lec8, lec9
IlyaOrlov/PythonCourse pull request #270
Opened 2020-08-21 10:11 UTC by tatyanashashalina

2020-09-07 12:29 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task3.py
> +def sort(arr):
Да, она работает.

2020-09-07 12:50 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task3.py
> +    min = 0
Исправила.

2020-09-07 12:51 UTC, tatyanashashalina commented on Practice/shashalina/Tasks 18.08.2020.py
> +        self.parseText = text.split(self.symbol)
Исправила.

2020-09-07 15:55 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task3.py
> +def sort(arr):
До исправления у вас менялся только нулевой элемент:
```python
            arr[number_min] = arr[0]
            arr[0] = min
```
Теперь все ОК.

2020-09-07 16:16 UTC, IlyaOrlov requested changes
Папку .idea лучше добавить в .gitignore и удалить.

2020-09-07 16:16 UTC, IlyaOrlov commented on Practice/shashalina/Tasks 18.08.2020.py
> +        sys.stdout.write(n)
А чем print плох? Или это для эксперимента?)

2020-09-07 16:16 UTC, IlyaOrlov commented on Practice/shashalina/Tasks 18.08.2020.py
> +        self.parseText = text.split(self.symbol)
Увы, нет. split сразу создает в памяти весь список, поэтому его использовать не стоит.

2020-09-07 16:16 UTC, IlyaOrlov commented on Practice/shashalina/Tasks 18.08.2020.py
> +        if self.i is not len(self.parseText):
is и is not проверяют не значения переменных, а их id (фактически, адреса). У небольших чисел адреса действительно будут совпадать (Python оптимизирует работу с памятью), но если длина строки получится достаточно большой, результат окажется неожиданным:
```python
>>> a = 1000
>>> b = 1000
>>> a is b
False
```
Используйте is и is not для сравнения с None, True, False, или когда уверены, что вам нужно сравнить именно адреса, а не значения объектов.

2020-09-07 16:16 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task4.py
> +
А что вернется в ветке if?

2020-09-07 16:16 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task4.py
> +        fw = open(obj, "w+")
А почему "r"+ и "w+"?

2020-09-07 16:16 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task4.py
> +        lst_file_str = file_str.split("    ")
Строки 17-23 и 32-38 можно заменить обычным replace'ом.

2020-09-07 16:16 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task5.py
> +  obj.replace(str, str(int(str)*2))
Код нерабочий. Хотя бы потому, что вы переопределили встроенную функцию str в строке 13.

2020-09-18 18:10 UTC, tatyanashashalina commented on Practice/shashalina/Tasks 18.08.2020.py
> +        sys.stdout.write(n)
Скорее да.

2020-09-18 18:11 UTC, tatyanashashalina commented on Practice/shashalina/Tasks 18.08.2020.py
> +        if self.i is not len(self.parseText):
Исправила.

2020-09-18 18:26 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task4.py
> +        lst_file_str = file_str.split("    ")
Но у меня функция реализована так, что она заменяет пробелы на табуляции и табуляции на пробелы в случае если есть и то и другое одновременно, в более общем случае она тоже должна сработать

2020-09-18 18:26 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task4.py
> +        fw = open(obj, "w+")
По другому не получалось открывать на чтение и запись.

2020-09-18 19:26 UTC, IlyaOrlov requested changes
Хорошо. Осталось 4 вопроса/замечания

2020-09-18 19:26 UTC, IlyaOrlov commented on Practice/shashalina/Tasks 18.08.2020.py
> +iter = MyIter("The cat see a tree", " ")
Теперь все замечательно, только iter - это тоже встроенная функция. Поэтому для переменной лучше придумать другое имя.

2020-09-18 19:26 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task4.py
> +        fw = open(obj, "w+")
Странно. И в чем была ошибка? Если что, файл text.txt с входными данными создается отдельно, и, если он существует, то на чтение откроется без проблем.

2020-09-18 19:26 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task4.py
> +        lst_file_str = file_str.split("    ")
Понятно. Оригинальная интерпретация задания)

2020-09-18 19:43 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task5.py
> +  obj.replace(str, str(int(str)*2))
Да, здесь совсем что-то не то...

2020-09-18 19:45 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task4.py
> +
Можно предположить что new_obj?

2020-09-18 19:45 UTC, tatyanashashalina commented on Practice/shashalina/Tasks 18.08.2020.py
> +        if self.i is not len(self.parseText):
Исправлено

2020-09-18 19:46 UTC, tatyanashashalina commented on Practice/shashalina/20.08.2020.py
> +import numpy
Добавила другой способ.

2020-09-18 20:19 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task5.py
> +    if obj.find(key) > -1:
Эта строка здесь явно лишняя: сначала по строке пробегает find, чтоб найти key, потом пробегает replace, чтоб опять найти key и на этот раз заменить.

2020-09-18 20:23 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task4.py
> +
Почему бы тогда не вынести return new_obj из if .. else (как общий множитель а скобки), если и в if, и в else возвращается одно и то же.

2020-09-25 14:14 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task4.py
> +        fw = open(obj, "w+")
Исправила на "r"и "w". Открывается. Ошибки нет - в чем была ошибка воспроизвести не смогу.

2020-09-25 14:14 UTC, tatyanashashalina commented on Practice/shashalina/lec4 task4.py
> +
Исправила.

2020-09-25 14:23 UTC, IlyaOrlov commented on Practice/shashalina/lec4 task4.py
> +        fw = open(obj, "w+")
Хорошо. Возможно, файла для чтения не было, или он находился по другому пути.

2020-09-25 14:31 UTC, IlyaOrlov requested changes

2020-09-25 14:31 UTC, IlyaOrlov commented on Practice/shashalina/lec6task4.py
> +def myCombination(str):
Переименуйте аргумент str. str - это имя встроенной функции.

2020-10-12 12:22 UTC, IlyaOrlov approved these changes

2020-10-12 12:22 UTC, merged