pep8+lec2+lec4+lec5
IlyaOrlov/PythonCourse pull request #274
Opened 2020-08-28 18:27 UTC by cool07

2020-08-29 20:53 UTC, IlyaOrlov commented on Practice/Karpov_A/t4_2.py
> +    for i, k in enumerate(num):
Если с enumerate, то лучше проще:
```python
def numlsit(num):
    for i, k in enumerate(num, 1):
        print(f"{i} цифра равна {k}")
```

2020-08-29 21:11 UTC, IlyaOrlov requested changes

2020-08-29 21:11 UTC, IlyaOrlov commented on Practice/Karpov_A/t5_3.py
> +                return "Output: {}".format(exem)
Геттер должен возвращать значение, того же типа, что и value в сеттере. Иначе ожидаемое равенство результатов 1-го и 2-го print (до и после САМОприсваивания, соответственно) в следующем примере внезапно обернется сюрпризом:
```python
print(wrap.content)
wrap.content = wrap.content
print(wrap.content)
```

2020-08-29 21:11 UTC, IlyaOrlov commented on Practice/Karpov_A/t2_3.py
> +        if persons[number].x == spec.x:
Тема изменения действий персонажа при подборе предметов как-то не раскрыта. Ожидается, что после подбора какого-нибудь бонуса, при вызове в дальнейшем у персонажа, например, метода fly вместо "I can fly" будет печататься "I can fly very fast".

2020-09-01 14:14 UTC, cool07 commented on Practice/Karpov_A/t4_2.py
> +    for i, k in enumerate(num):
Согласен. Так проще.

2020-09-01 14:27 UTC, cool07 commented on Practice/Karpov_A/t4_3.py
> +    for i in range(len(arr) - 1):
ОК)))
def sorting(arr):
    for i in range(len(arr)):
        min = i
        for j in range (i + 1, len(arr)):
            if arr[j] < arr[min]:
                min = j
        arr[i], arr[min] = arr[min], arr[i]
    print(arr)


arr = [0, -5, 34, 2, 3, -59]
sorting (arr)

2020-09-01 14:27 UTC, cool07 commented on Practice/Karpov_A/t4_3.py
> +    for i in range(len(arr) - 1):
Или загрузить исправления?

2020-09-01 14:37 UTC, cool07 commented on Practice/Karpov_A/t5_2.py
> +class Man:
import time
import random
from t5_1 import Man

class Pupil(Man):
    def __init__(self, name):
        self.name = name

    def solve_task(self):
        time.sleep(random.randint(3,6))
        print("I'm not ready yet")

Tom = Pupil('Tom')
print(Tom.solve_task())

2020-09-01 14:38 UTC, cool07 commented on Practice/Karpov_A/t5_2.py
> +class Man:
Спасибо, исправил.

2020-09-01 15:10 UTC, IlyaOrlov commented on Practice/Karpov_A/t4_3.py
> +    for i in range(len(arr) - 1):
Тогда уж скорее while напрашивается. Загружать новый вариант не обязательно.

2020-09-01 15:11 UTC, cool07 commented on Practice/Karpov_A/t5_3.py
> +                return "Output: {}".format(exem)
Так?
@property
    def content(self):
        try:
            with open(self.filepath, "r") as file:
                exem = file.read()
                return "Output: {}".format(exem)

        except IOError as file:
            return "Output: File does't exist"

    @content.setter
    def content(self, value):
        self.value = value
        with open(self.filepath, "w") as file:
            file.write(self.value)

2020-09-01 15:12 UTC, cool07 commented on Practice/Karpov_A/t2_3.py
> +        if persons[number].x == spec.x:
Согласен, всё выглядит очень примитивно(((

2020-09-01 16:40 UTC, IlyaOrlov commented on Practice/Karpov_A/t2_3.py
> +        if persons[number].x == spec.x:
Ну я бы не сказал, что все примитивно, но именно указанное замечание стоит учесть, т.к. оно хорошо отражает частые проблемы проектирования классов.

2020-09-01 16:42 UTC, IlyaOrlov commented on Practice/Karpov_A/t5_3.py
> +                return "Output: {}".format(exem)
Нет. Вот если в геттере сделаете просто return exem, тогда будет ОК.

2020-09-08 14:56 UTC, cool07 commented on Practice/Karpov_A/t5_2.py
> +print(Tom.solve_task())
print("I'm not ready yet")

Tom = Pupil('Tom')
print(f"{Tom.name}:", end=" ")
Tom.solve_task()

2020-09-08 15:04 UTC, cool07 commented on Practice/Karpov_A/t5_3.py
> +                return "Output: {}".format(exem)
with open(self.filepath, "r") as file:
                return file.read()
                
        except IOError as file:
            return "Output: File does't exist"

2020-09-08 15:09 UTC, cool07 commented on Practice/Karpov_A/t4_3.py
> +    for i in range(len(arr) - 1):
Я запутался((

2020-09-09 11:18 UTC, IlyaOrlov commented on Practice/Karpov_A/t4_3.py
> +    for i in range(len(arr) - 1):
На самом деле оба варианты равнозначны, тут больше дело вкуса (если я использую переменную цикла i, j под индекс элемента списка, то предпочитаю while, если под сам элемент - то for). Так что с двумя for тоже норм.

2020-09-09 11:20 UTC, IlyaOrlov commented on Practice/Karpov_A/t5_3.py
> +                return "Output: {}".format(exem)
Да, так лучше. Осталось закоммитить.

2020-09-09 11:20 UTC, IlyaOrlov commented on Practice/Karpov_A/t5_2.py
> +class Man:
ОК. Надо закоммитить.

2020-09-09 11:22 UTC, IlyaOrlov commented on Practice/Karpov_A/t5_2.py
> +print(Tom.solve_task())
Так лучше. Еще лучше, если self.name выводить прямо внутри solve_task.

2020-09-09 11:22 UTC, IlyaOrlov reviewed
Ожидается исправление оставшихся замечаний.

2020-09-09 15:47 UTC, cool07 commented on Practice/Karpov_A/t2_3.py
> +        if persons[number].x == spec.x:
Хорошо

2020-09-09 15:50 UTC, cool07 commented on Practice/Karpov_A/t5_2.py
> +class Man:
Сделал.

2020-09-09 15:52 UTC, cool07 commented on Practice/Karpov_A/t5_3.py
> +                return "Output: {}".format(exem)
Закоммитил

2020-09-09 19:30 UTC, IlyaOrlov approved these changes

2020-09-09 19:30 UTC, merged