aulov_r
IlyaOrlov/PythonCourse pull request #275
Opened 2020-08-30 19:54 UTC by Rusbrus

2020-08-31 18:35 UTC, IlyaOrlov commented on Practice/aulov_r/5lec3.py
> +        self._filepath = 'delete file'
Надо удалить файл физически, используя методы модуля os.

2020-08-31 18:38 UTC, IlyaOrlov requested changes

2020-08-31 18:38 UTC, IlyaOrlov commented on Practice/aulov_r/5lec3.py
> +            a.read()
Так, конечно, тоже правильно все сработает, но  лучше писать всю работу с файлом прямо в try. Если исключение случится при открытии файла, то и read, и close все равно не будут выполнены.

2020-09-02 17:25 UTC, Rusbrus commented on Practice/aulov_r/5lec3.py
> +        self._filepath = 'delete file'
тогда так
os.remove(self.filepath)

2020-09-02 17:30 UTC, Rusbrus commented on Practice/aulov_r/5lec3.py
> +            a.read()
еще можно сделать так: return ('not file')

2020-09-02 17:43 UTC, IlyaOrlov commented on Practice/aulov_r/5lec3.py
> +        self._filepath = 'delete file'
Да. Именно так и нужно.

2020-09-02 17:44 UTC, IlyaOrlov commented on Practice/aulov_r/5lec3.py
> +            a.read()
Я бы совместил текущий print и явный return None

2020-09-06 16:42 UTC, IlyaOrlov requested changes

2020-09-06 16:42 UTC, IlyaOrlov commented on Practice/aulov_r/7lec1.py
> +cc = aa - bb
А как же учесть выходные дни?

2020-09-07 17:53 UTC, IlyaOrlov commented on Practice/aulov_r/7lec1.py
> +cc = aa - bb
Сравнение строк выполняется гораздо медленнее сравнения чисел. Поэтому лучше данные из строк преобразовывать в datetime.date и определять рабочий ли день при помощи метода weekday()
И было бы лучше, если б код вы все-таки закоммитили в гит.

2020-09-08 10:31 UTC, Rusbrus commented on Practice/aulov_r/7lec1.py
> +cc = aa - bb
Понял переделаю

2020-09-09 11:11 UTC, IlyaOrlov commented on Practice/aulov_r/7lec1.py
> +cc = aa - bb
Почему бы содержимое 7lec1(1).py не скопировать в 7lec1.py, а 7lec1(1).py удалить?

2020-09-09 11:12 UTC, IlyaOrlov commented
Ожидаются исправления по оставшимся замечаниям.

2020-09-09 18:58 UTC, Rusbrus commented
Вроде все поправил

2020-09-09 20:09 UTC, Rusbrus commented
Все сделал

2020-09-09 20:53 UTC, IlyaOrlov approved these changes

2020-09-09 20:53 UTC, merged