lec7 + razm
IlyaOrlov/PythonCourse pull request #277
Opened 2020-08-31 18:48 UTC by Kate-Shipunova

2020-08-31 19:17 UTC, IlyaOrlov requested changes

2020-08-31 19:17 UTC, IlyaOrlov commented on Practice/E_Shipunova/7.1.py
> +def working_days(first_data, second_data):
Почему-то working_days(datetime.datetime(2020, 8, 24), datetime.datetime(2020, 8, 30)) выдает 6 дней, а должно быть 5.

2020-08-31 19:17 UTC, IlyaOrlov commented on Practice/E_Shipunova/7.3load.py
> +class Human:
Human лучше вынести в отдельный файл и заимпортировать в 7.3dump и 7.3load, чтоб не дублировать код.

2020-08-31 19:17 UTC, IlyaOrlov commented on Practice/E_Shipunova/7.4.py
> +                    is_empty = not bool(sorted(Path(path_of_item).rglob('*')))
Обязательно ли делать эту проверку? Может, рекурсивный вызов del_in_dir сам разберется, есть, что удалять в папке, или нет?

2020-08-31 19:17 UTC, IlyaOrlov commented on Practice/E_Shipunova/razminka(git).py
> +import re
Отлично. На самом деле (я как-то упустил этот момент) достаточно было найти сочетания команд (git pull, git commit и т.д.). Однако, увлекшись вашим вопросом, я тоже попробовал найти решение, чтоб находились полные команды с аргументами. Получилось следующее:
```python
import re

with open("git.txt") as f:
    res = []
    for s in f:
        res.extend(re.findall(' (git [a-z]+ ?-{0,2}[mb]? ?[^-)\n]*)[ )\n]', s))
        res.extend(re.findall('"(git [a-z]+ ?-{0,2}[mb]? ?.*)"', s))
    print(res)
```

2020-09-01 19:20 UTC, Kate-Shipunova commented on Practice/E_Shipunova/7.1.py
> +def working_days(first_data, second_data):
Оказалось ещё, что при стартовой дате, приходящейся на выходные, результат тоже некорректный.

2020-09-01 19:34 UTC, Kate-Shipunova commented on Practice/E_Shipunova/7.4.py
> +                    is_empty = not bool(sorted(Path(path_of_item).rglob('*')))
Данная проверка, как вы верно заметили, необязательна. Действительно, при рекурсивном вызове ф-ции для пустой папки в whileе в цикл for мы не зайдем (перебирать в нем просто нечего), будут выполнены строки 51, 52, 53, и мы вернемся на предыдущий уровень рекурсии.
Зачем её пишу? Рекурсия уже обсуждалась, и исходя из этого - в целях экономии ресурсов.
Вызов ф-ции - операция затратная, хотя и выполнение проверки не бесплатно. Как я понимаю, все же оптимальнее выполнить проверку, чем создавать ф-цию со всем ее окружением, отрабатывать несколько строк и "выпрыгивать" из нее (и так, при самом консервативном подходе, в течение 2х минут).

2020-09-01 19:36 UTC, Kate-Shipunova commented on Practice/E_Shipunova/razminka(git).py
> +import re
Очень детальный подход, и комментарий у '... commit -m' захватили. Здорово!
Хотелось, конечно, красиво - одной строчкой все команды извлечь.

2020-09-01 19:50 UTC, IlyaOrlov commented on Practice/E_Shipunova/7.4.py
> +                    is_empty = not bool(sorted(Path(path_of_item).rglob('*')))
Это правильно, что вы обратили внимание на ресурсоемкость лишнего вызова функции (в частности, рекурсивного вызова). Однако, если сама проверка сопряжена с вызовом функции и всеми сопутствующими затратами, выгода от этой проверки весьма сомнительна.

2020-09-01 19:55 UTC, IlyaOrlov commented on Practice/E_Shipunova/razminka(git).py
> +import re
Спасибо) Хотелось бы все одной строкой сделать, но не вижу никаких способов заставить re различать кавычки, окружающие аргумент команды, и кавычки, окружающие саму команду, хотя и не исключаю, что такие способы существуют.

2020-09-01 19:56 UTC, IlyaOrlov approved these changes

2020-09-01 19:57 UTC, merged