tasks for lec 6, 7, 8 are done
IlyaOrlov/PythonCourse pull request #279
Opened 2020-09-05 11:36 UTC by Koeco97

Komissarova O

2020-09-06 16:19 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/bonus.py
> +    left_list = reverse_sort_numbers(arr[:mid])
Это хорошо, что вы разобрались с сортировкой слиянием, но достаточно было просто воспользоваться встроенным методом sort или функцией sorted (реализуют алгоритм быстрой сортировки). Впрочем, подход правильный, и итоговая алгоритмическая сложность оптимальная. Отлично!

2020-09-06 16:38 UTC, IlyaOrlov requested changes

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task10.py
> +            number1 = float(str(self).replace(",", "."))
Во всех методах повторяется почти одни и те же операции (в основном, приведение к float). Можно было инкапсулировать общий код в магический метод \_\_float\_\_ и реализовывать, например, \_\_sub\_\_ как Money(str(float(self) - float(other)).split('.')), строки или даже добавить в конструктор Money возможность создания объекта из float(), а не из

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task3.py
> +    if len(args) >= 2:
Лучше elif, чтоб избежать лишних проверок, если len(args)==1

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task3.py
> +    if len(args) == 3:
Этот if лучше сдвинуть под if len(args) >= 2

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task3.py
> +        while position >= stop:
Получается 2 почти одинаковых цикла. Нельзя ли обойтись одним, инкапсулировав проверку position >= stop или position <= stop, например, в лямбду.

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task4.py
> +print(to_title('what a wonderful world'))
Ожидается, что будет все-таки **W**hat **A** **W**onderful **W**orld, а не **W**hat a wonderful world.

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task6.py
> +print(my_format('{1}, {0}, {2}', 'a', 'b', 'c'))
А если индекс состоит более, чем из двух цифр:
print(my_format('{10}, {0}, {2}', 'a', 'b', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'u'))?

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task7.py
> +    if Path(destination).is_file():
Лишняя проверка. Достаточно попробовать открыть файл в режиме 'x'.

2020-09-06 16:38 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task8.py
> +    for root, dirs, files in os.walk(source):
По заданию предполагалось, что вы воспользуетесь вашей же функцией copy_file из task7.

2020-09-12 16:07 UTC, Koeco97 commented on Practice/o_komissarova/for_lec8/task3.py
> +        while position >= stop:
не смогла сделать с лямбдой, остальное поправила

2020-09-12 17:29 UTC, IlyaOrlov commented on Practice/o_komissarova/for_lec8/task3.py
> +        while position >= stop:
С lambda можно так:
```python
f = (lambda a, b: a < b) if step > 0 else (lambda a, b: a >= b)
while f(position, stop):
```

2020-09-12 17:32 UTC, IlyaOrlov approved these changes

2020-09-12 17:32 UTC, merged