Viktor gartcev, lec2-7
IlyaOrlov/PythonCourse pull request #281
Opened 2020-09-09 19:40 UTC by ViktorGa

2020-09-09 21:13 UTC, IlyaOrlov requested changes

2020-09-09 21:13 UTC, IlyaOrlov commented on Practice/ViktorGa/L4T1.py
> +        if i % 3 == 0:
В этом случае FizzBuzz у вас никогда не напечатается, т.к. все, что делится на 15, делится также и на 3, и на 5.

2020-09-09 21:13 UTC, IlyaOrlov commented on Practice/ViktorGa/L4T4.py
> +        str = f.read()
Не следует использовать ключевые слова Python (в данном случае str) в качестве имен переменных.

2020-09-09 21:13 UTC, IlyaOrlov commented on Practice/ViktorGa/L4T4.py
> +            f.close()
Можно ли оптимизировать код, вынеся общие участки (f.write, f.close, return True), так сказать, "за скобки"?

2020-09-09 21:13 UTC, IlyaOrlov commented on Practice/ViktorGa/L4T5.py
> +str = 'и вот я успел сделать python'
str - имя функции, приводящей к строковому типу.

2020-09-09 21:13 UTC, IlyaOrlov commented on Practice/ViktorGa/L5T2.py
> +class Man:
Почему бы просто не импортировать Man из L5T1.py?

2020-09-09 21:13 UTC, IlyaOrlov commented on Practice/ViktorGa/L7T1.py
> +    first_day = first_data.strftime("%A")
Лучше использовать метод weekday(), позволяющий получить числовое представление дня недели. Числа сравниваются гораздо быстрее, чем строки.

2020-09-10 16:13 UTC, ViktorGa commented on Practice/ViktorGa/L4T1.py
> +        if i % 3 == 0:
Порядок проверки изменён

2020-09-10 16:14 UTC, ViktorGa commented on Practice/ViktorGa/L4T4.py
> +            f.close()
Вынесены f.close, return True

2020-09-10 16:14 UTC, ViktorGa commented on Practice/ViktorGa/L4T5.py
> +str = 'и вот я успел сделать python'
Исправлено

2020-09-10 16:14 UTC, ViktorGa commented on Practice/ViktorGa/L5T2.py
> +class Man:
Класс заменен на импортный

2020-09-10 16:15 UTC, ViktorGa commented on Practice/ViktorGa/L7T1.py
> +    first_day = first_data.strftime("%A")
Спасибо, заменил

2020-09-10 21:00 UTC, IlyaOrlov commented on Practice/ViktorGa/L4T1.py
> +        if i % 3 == 0:
Ну еще Fizz и FizzBuzz тогда уж следовало бы местами поменять. Но, впрочем, это не принципиальная ошибка.

2020-09-10 21:04 UTC, IlyaOrlov commented on Practice/ViktorGa/L7T1.py
> +    first_day = first_data.strftime("%A")
Хорошо. Только weekday() возвращает число (порядковый номер дня недели), поэтому first_day никогда не будет равен ни "Saturday", ни "Sunday" (но может быть равен 5 или 6 соответственно).

2020-10-05 18:01 UTC, ViktorGa commented on Practice/ViktorGa/L4T1.py
> +        if i % 3 == 0:
Совсем ослеп. Спасибо, поправил

2020-10-05 20:17 UTC, ViktorGa commented on Practice/ViktorGa/L7T1.py
> +    first_day = first_data.strftime("%A")
При проверке он еще и криво считал в случае, если диапазон был выходной-выходной. Обрабатывать условиями громоздко, поэтому переписал. Проверил, работает

2020-10-05 20:21 UTC, IlyaOrlov approved these changes

2020-10-05 20:21 UTC, merged