lec9
IlyaOrlov/PythonCourse pull request #286
Opened 2020-09-10 14:48 UTC by Kate-Shipunova

2020-09-10 21:15 UTC, IlyaOrlov requested changes
9.1 и 9.2 выполнены превосходно, но по 9.3 есть существенное замечание!

2020-09-10 21:15 UTC, IlyaOrlov commented on Practice/E_Shipunova/9.3.py
> +    pool = Pool(processes=3)
Все-таки данную задачу требовалось реализовать именно с использованием потоков. А приватность данных для потока невозможная, если мы используем глобальную переменную. Нужно либо использовать локальные переменные, либо threading.local.

2020-09-11 14:58 UTC, Kate-Shipunova commented on Practice/E_Shipunova/9.3.py
> +    pool = Pool(processes=3)
Мысль была, что либо звездочка у задачки лишняя, либо я неправильно поняла задание. Второе оказалось истиной.
И... Ольга сегодня сделала рассылку. ОГРОМНОЕ спасибо, что не отправили обратно  в 1-вую группу!

2020-09-11 15:54 UTC, IlyaOrlov commented on Practice/E_Shipunova/9.3.py
> +    pool = Pool(processes=3)
Теперь все ОК.
Не за что. Распределение по группам осуществлялось по результатам контрольной, домашних заданий, активности на занятии. Так что у вас просто не было шансов вернуться в 1-ю группу) Ну только если по собственному желанию)

2020-09-11 15:54 UTC, IlyaOrlov approved these changes

2020-09-11 15:54 UTC, merged