lec10
IlyaOrlov/PythonCourse pull request #293
Opened 2020-09-17 17:57 UTC by Kate-Shipunova

2020-09-17 20:30 UTC, IlyaOrlov requested changes

2020-09-17 20:30 UTC, IlyaOrlov commented on Practice/E_Shipunova/10.1Server.py
> +    shifr = list(conn.recv(1024).decode())  # get shifr from client
Зачем преобразовывать полученное в список? Все равно в последующем вы не меняете его элементы, а создаете новый список.

2020-09-17 20:30 UTC, IlyaOrlov commented on Practice/E_Shipunova/10.1Server.py
> +        for key in secret.keys():
Не проще ли было бы инвертировать словарь, чтоб искать в нем по ключу, а не по значению: res.append(secret.get(ch, ch))?

2020-09-18 18:28 UTC, Kate-Shipunova commented on Practice/E_Shipunova/10.1Server.py
> +        for key in secret.keys():
Рекомендации учтены, добавлен обработчик исключения на случай некорректного шифра от клиента.

2020-09-18 19:28 UTC, IlyaOrlov approved these changes

2020-09-18 19:28 UTC, merged