8lec(3,5) and 9lec(1)
IlyaOrlov/PythonCourse pull request #294
Opened 2020-09-18 16:47 UTC by Rusbrus

2020-09-18 18:06 UTC, IlyaOrlov commented
Попробуйте подтянуть содержимое с IlyaOrlov:master в свой репозиторий. А то в PullRequest попали уже проверенные задачи. Команда должна выглядеть примерно так:
git pull https://github.com/IlyaOrlov/PythonCourse master --allow-unrelated-histories

2020-09-18 19:30 UTC, IlyaOrlov commented on Practice/aulov_r/9lec1.py
> +if __name__ == '__main__':
Какой вывод по задаче? Что лучше использовать?

2020-09-20 16:40 UTC, Rusbrus commented on Practice/aulov_r/9lec1.py
> +if __name__ == '__main__':
По мне что лучше я затрудняюсь сказать, так как поиск простых чисел в заданном диапазоне с помощью функции, многопоточности или многопроцессорности за этим было интересно посмотреть. Через функцию позволило легко автоматизировать процесс и найти достаточно быстро простые числа в заданных диапазонах. Через многопоточность из за синхронизируются потоков через GIL, одновременно выполняется только один поток и переменные у потоков общие. И это притормозило результат и буквально на сотые секунды. Через многопроцессорность это поинтереснее с помощью обработки нескольких процессов одновременно несколькими процессорами способствовало уменьшить скорость работы, время выполнение было наименьшим.

2020-09-20 17:06 UTC, IlyaOrlov requested changes

2020-09-20 17:06 UTC, IlyaOrlov commented on Practice/aulov_r/9lec1.py
> +if __name__ == '__main__':
Нужно привести итоговое время выполнения задачи для последовательного выполнения, для распараллеливания при помощи потоков и для распараллеливания при помощи процессов. Рассуждения правильные, но нужно подкрепить их фактическими результатами. На собеседовании потребовался бы однозначный ответ: "такой вариант лучше, потому что...". При этом основные критерии оптимальности - это время (в первую очередь) и память - чем меньше расход, тем лучше.

2020-09-21 06:58 UTC, Rusbrus commented on Practice/aulov_r/9lec1.py
> +if __name__ == '__main__':
Если так, то вариант при помощи процессов лучше, так как нагрузка при этом на CPU значительно меньше и время выполнения выше составила 1,06 при том что при последовательно выполнения затратило времени 1,62, а при распараллеливания при помощи потоков времени потребовалось 1,68

2020-09-21 09:14 UTC, IlyaOrlov commented on Practice/aulov_r/9lec1.py
> +if __name__ == '__main__':
Да, почти все правильно, только "нагрузка при этом на CPU значительно меньше" - неоднозначный и сомнительный критерий оптимальности. Если, допустим, алгоритм неэффективный, программа работает долго из-за всяких блокировок, и процессор при этом загружен на 20%, то это хуже, чем если программа загрузит процессор на 100%, но выполнится при этом быстро. А вот время - да, это то, на нужно смотреть.

2020-09-22 18:09 UTC, Rusbrus commented
я файлы добавил отдельно, как вы просили

2020-09-22 19:32 UTC, IlyaOrlov commented
> я файлы добавил отдельно, как вы просили

Хорошо. Новую ветку https://github.com/IlyaOrlov/PythonCourse/pull/297 утвердил. Данную ветку (https://github.com/IlyaOrlov/PythonCourse/pull/294), можно закрыть (кнопка Close).

2020-09-23 11:06 UTC, closed without merging