Practice 9 is ready
IlyaOrlov/PythonCourse pull request #298
Opened 2020-09-23 13:26 UTC by MarinaSpasskova

2020-09-23 13:36 UTC, IlyaOrlov commented on Practice/Postnikova/practice_9_task_1.py
> +    for i in range(3):
На самом деле под "запустить 3 раза" подразумевалось как раз три запуска с аргументами (10000, 3), (20000, 10001) и (30000, 20001) - по одному на каждый кортеж.

2020-09-23 13:46 UTC, IlyaOrlov requested changes

2020-09-23 13:46 UTC, IlyaOrlov commented on Practice/Postnikova/practice_9_task_1.py
> +
Для полноты сравнения не хватает примера с последовательным запуском (без потоков и процессов).

2020-09-23 13:46 UTC, IlyaOrlov commented on Practice/Postnikova/practice_9_task_1.py
> +
Какой вариант запуска в итоге лучше и почему?

2020-09-23 13:46 UTC, IlyaOrlov commented on Practice/Postnikova/practice_9_task_1.py
> +    p_result = time.time() - start_2
Поскольку start_2 вы определили до запуска потоков, время p_result = time.time() - start_2 включает в себя не только время работы процессов, но и время работы потоков, поэтому оно априори будет больше времени работы потоков.

2020-09-23 13:46 UTC, IlyaOrlov commented on Practice/Postnikova/practice_9_task_2.py
> +for j in range(3):
А здесь в чем сакральный смысл тройного запуска потоков? И кстати, почему именно потоков?

2020-09-23 13:56 UTC, MarinaSpasskova commented on Practice/Postnikova/practice_9_task_1.py
> +    for i in range(3):
Исправлено

2020-09-24 08:49 UTC, MarinaSpasskova commented on Practice/Postnikova/practice_9_task_1.py
> +
Добавлено

2020-09-24 08:50 UTC, MarinaSpasskova commented on Practice/Postnikova/practice_9_task_1.py
> +
Вывод добавлен

2020-09-24 08:51 UTC, MarinaSpasskova commented on Practice/Postnikova/practice_9_task_1.py
> +    p_result = time.time() - start_2
Да, просмотрела эту строчку! Исправлено.

2020-09-24 08:59 UTC, MarinaSpasskova commented on Practice/Postnikova/practice_9_task_2.py
> +for j in range(3):
Никакого смысла, по невнимательности сделано, исправлено. Изначально сделала с процессами, потому что формально для параллельного выполнения  нужны именно процессы, потом, подумала, что если требуется вернуть результат работы функции, то проще организовать это с потоками, чем взаимодействие между процессами. Исправлено на процессы.

2020-09-24 11:11 UTC, IlyaOrlov commented on Practice/Postnikova/practice_9_task_1.py
> +
Хорошо. Только в описании итога для threads обязательно стоит упомянуть GIL, из-за которого параллелизм при помощи потоков в принципе нереализуем.

2020-09-24 11:18 UTC, IlyaOrlov commented on Practice/Postnikova/practice_9_task_2.py
> +for j in range(3):
На самом деле процессы, конечно, несколько тяжеловесней, чем потоки. Больше времени уходит на создание процесса. Но если задача использует процессор и вычислений действительно много, то процессам альтернативы нет. Как я уже упомянул в другом комментарии, из-за GIL в Python потоки не позволяют реализовать одновременное выполнение задач (то, что понимается под термином "параллелизм"). Единственное, для чего они применимы  - это для конкурентности (т.е. независимого асинхронного выполнения задач), когда задачи связаны с вводом/выводом, получением данных по сети и всем, что не использует процессор.

2020-09-24 11:46 UTC, MarinaSpasskova commented on Practice/Postnikova/practice_9_task_1.py
> +
Дополнение про GIL добавлено

2020-09-24 12:43 UTC, IlyaOrlov approved these changes

2020-09-24 12:43 UTC, merged