lec2,4,5
IlyaOrlov/PythonCourse pull request #303
Opened 2020-09-28 17:32 UTC by Oigul

2020-09-28 19:58 UTC, IlyaOrlov requested changes

2020-09-28 19:58 UTC, IlyaOrlov commented on Practice/Salakhetdinova/lab4_5.py
> +        if key in string:
Лишнее условие. Из-за этого key ищется в string дважды.

2020-09-28 19:58 UTC, IlyaOrlov commented on Practice/Salakhetdinova/lab4_3.py
> +def sort(arr):
Не работает. 
Например, для arr = [1, 5, 3] результат - [1, 3, 3]
Всегда стоит проверять алгоритмы в первую очередь на предопределенных (неслучайных) данных.

2020-10-05 17:49 UTC, Oigul commented on Practice/Salakhetdinova/lab4_3.py
> +def sort(arr):
Спасибо! исправлю

2020-10-05 19:09 UTC, IlyaOrlov commented on Practice/Salakhetdinova/lab4_3.py
> +        temp = arr[i]
OK. Только строки 9-11 можно сократить:
```python
arr[i], arr[min_value] = arr[min_value], arr[i]
```

2020-10-05 19:10 UTC, IlyaOrlov approved these changes

2020-10-05 19:10 UTC, merged