all pract added
IlyaOrlov/PythonCourse pull request #310
Opened 2020-10-12 18:02 UTC by asintsov

2020-10-12 21:53 UTC, IlyaOrlov commented on Practice/sintsov/a_sintsov_exam_1.py
> +        if (step > 0):
Код в блоках if и elif почти одинаковый. Нельзя ли его как-то упростить (например, убрать операции с > и < в lambda).

2020-10-12 21:57 UTC, IlyaOrlov commented on Practice/sintsov/a_sintsov_exam_1.py
> +    lst = [ch for ch in line if ch == symb]
Списковые выражения - это, конечно, изящно, но не всегда оптимально. Задачу можно решить, не расходуя память на дополнительный список.

2020-10-12 22:24 UTC, IlyaOrlov requested changes

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/a_sintsov_exam_1.py
> +        sh.copytree(dirSource, dirDest)
Подразумевалось, что данную задачу вы решите, рекурсивно используя свою функцию из задания 7.

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/tank_game.py
> +    def move(self, direction, item2):
Вопрос на понимание: если нам потребуется добавить в игру возможность изменения действий танка при подборе определенных предметов (например, при наезде на некоторую координату, которой соответствует некий бонус, танк получает возможность перелетать на несколько шагов сразу, или двигаться зигзагами, т.е. метод move для него поменяется кардинально), как это можно будет реализовать?

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_10/task_10_server.py
> +        lst.append(d.get(c) if d.get(c) else '*')
Значение по умолчанию можно указать прямо в get: d.get(c, '*')

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_4.py
> +    print("".join(str(el)+" " for el in ["FizzBuzz" if (x % 3 == 0 and x % 5 == 0)
В кавычках перед join как раз и указывается разделитель. Не нужно его указывать после el.

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_4.py
> +    print(*list(str(num)), sep = "\n")
OK, только требовалось вывести цифры в определенном формате:
1 цифра равна 1
2 цифра равна 0
и т.д

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_4.py
> +        lst[0], lst[x] = lst[x], lst[0] #почему не работает lst[0], lst[lst.index(min(lst))] = lst[lst.index(min(lst))], lst[0]
Потому что lst.index(min(lst)) слева считается уже после lst[0] = lst[lst.index(min(lst))], и таким образом всегда указывает на lst[0]

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_5.py
> +            print("File doesn't exist")
А что вернется в случае исключения?

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_5.py
> +            f.write(str(value))
Файл надо закрыть.

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_7.py
> +        pickle.dump(humans, outF)
Не лучше ли записывать humans в файл только один раз, после цикла? И считать потом будет проще.

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_9/task_9_1.py
> +    without_all()
Какой из способов оказался лучше?

2020-10-12 22:24 UTC, IlyaOrlov commented on Practice/sintsov/task_4.py
> +    f = open(fileDirection, "r")
Файл надо закрывать после использования.

2020-10-17 14:38 UTC, asintsov commented on Practice/sintsov/a_sintsov_exam_1.py
> +    return ("".join(el+' ' for el in lst))
Да, не дочитал про возможности .join(). Поправил

2020-10-17 14:38 UTC, asintsov commented on Practice/sintsov/a_sintsov_exam_1.py
> +    lst = [ch for ch in line if ch == symb]
Добавил вариант без спискового выражения

2020-10-17 14:39 UTC, asintsov commented on Practice/sintsov/a_sintsov_exam_1.py
> +    except FileExistException:
Добавил вариант с FileExistsError

2020-10-17 14:40 UTC, asintsov commented on Practice/sintsov/task_10/task_10_server.py
> +        lst.append(d.get(c) if d.get(c) else '*')
Спасибо, учту, поправил

2020-10-17 14:40 UTC, asintsov commented on Practice/sintsov/task_4.py
> +    print("".join(str(el)+" " for el in ["FizzBuzz" if (x % 3 == 0 and x % 5 == 0)
Ага, поправил

2020-10-17 14:41 UTC, asintsov commented on Practice/sintsov/task_5.py
> +            print("File doesn't exist")
Насколько понимаю, должна возвращаться пустая строка? Добавил

2020-10-17 14:41 UTC, asintsov commented on Practice/sintsov/task_5.py
> +            f.write(str(value))
Верно, забыл. Поправил

2020-10-17 14:42 UTC, asintsov commented on Practice/sintsov/task_9/task_9_1.py
> +    without_all()
Способ с мультипроцессорностью, как и ожидалось, самый быстрый на моем пк ... дописал ответ в файле

2020-10-17 14:44 UTC, asintsov commented on Practice/sintsov/task_4.py
> +    f = open(fileDirection, "r")
Согласен, поправил

2020-10-17 16:24 UTC, IlyaOrlov commented on Practice/sintsov/task_5.py
> +            print("File doesn't exist")
Если б вы ничего не написали бы, возвращалось бы None. Но явный return '' лучше, т.к. во-первых, он явный (значит, мы точно предусмотрели эту возможность), а во-вторых, когда во всех случаях функция возвращает значения одного и того же типа, она более понятна и предсказуема.

2020-10-17 16:31 UTC, IlyaOrlov requested changes

2020-10-17 16:31 UTC, IlyaOrlov commented on Practice/sintsov/task_4.py
> +    f = open(fileDirection, "r")
Так вы его закрываете в строке 37, уже после того, как переоткрыли на запись? На каждое открытие должно быть одно закрытие. В идеале здесь нужно использовать менеджер контекста with.

2020-10-17 16:31 UTC, IlyaOrlov commented on Practice/sintsov/a_sintsov_exam_1.py
> +    return line.count(symb)
В задании требовалось написать свою функцию, а не использовать строковый метод.

2020-10-17 18:47 UTC, IlyaOrlov requested changes

2020-10-17 18:47 UTC, IlyaOrlov commented on Practice/sintsov/task_11.py
> +class SQLiteManager:
Вот этот класс как раз следовало сделать менеджером контекста. А внутри него должны быть методы select и execute (методы имеются с маленькой буквы).

2020-10-17 18:47 UTC, IlyaOrlov commented on Practice/sintsov/task_11.py
> +    from contextlib import contextmanager
Все импорты стоит вынести в начало файла, чтоб были видны все зависимости данного модуля.

2020-10-17 20:26 UTC, asintsov commented on Practice/sintsov/task_11.py
> +    from contextlib import contextmanager
Ок, задумка была сделать класс удобным для импорта, где то видел в сети, что так пишут. Потом выяснил, что на импорт класса это никак не сказывается, а только если копировать сам текст класса. А так да, нас учили импорты вверху ставить, вопросов нет. Поправил

2020-10-17 20:27 UTC, asintsov commented on Practice/sintsov/task_11.py
> +class SQLiteManager:
Добавил второй вариант. Согласен, выглядит лучше

2020-10-17 20:28 UTC, asintsov commented on Practice/sintsov/a_sintsov_exam_1.py
> +    return line.count(symb)
Написал)

2020-10-17 20:29 UTC, asintsov commented on Practice/sintsov/task_4.py
> +    f = open(fileDirection, "r")
Поправил

2020-10-17 21:11 UTC, IlyaOrlov commented on Practice/sintsov/task_11.py
> +class SQLiteManager:
Если по тексту задания, то второй вариант подходит. Но с точки зрения практического применения ожидалось что-то вроде https://github.com/IlyaOrlov/PythonCourse/blob/master/Practice/E_Shipunova/11.1.py

2020-10-17 21:13 UTC, IlyaOrlov commented
Осталось 4 замечания без ответа.

2020-10-18 10:40 UTC, asintsov commented on Practice/sintsov/task_7.py
> +        pickle.dump(humans, outF)
Реализовал

2020-10-18 10:41 UTC, asintsov commented on Practice/sintsov/a_sintsov_exam_1.py
> +        if (step > 0):
Не смог понять, как условия убрать в lambda. Упростил по-другому

2020-10-18 10:51 UTC, asintsov commented on Practice/sintsov/a_sintsov_exam_1.py
> +        if (step > 0):
Разобрался

2020-10-18 19:59 UTC, asintsov commented on Practice/sintsov/tank_game.py
> +    def move(self, direction, item2):
да, приложение сыровато, только пробовал что то писать на пайтоне.
для реализации понадобилось переписать методы move и isRightDirection:
в move добавил аргумент - тип движения, в зависимости от которого внутри move выбирается, с помощью какой подфункции изменять координаты.
move теперь при помощи isRightDirection проверяет после движения, корректные ли координаты, если нет, откатывает сделанные изменения.
В playGame остается реализовать изменение переменной movingType в нужный момент для изменения способа движения

2020-10-18 21:25 UTC, IlyaOrlov commented on Practice/sintsov/tank_game.py
> +    def move(self, direction, item2):
ОК. Так тоже можно, если меняются только некоторые параметры действия. Если же анимация меняется принципиально (нужен другой алгоритм под тем же именем), можно вынести действия (типа move) в отдельную иерархию классов и связать ее с танками через композицию (см. паттерн Стратегия https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F))

2020-10-18 21:28 UTC, IlyaOrlov approved these changes

2020-10-18 21:28 UTC, merged