task 9 is done
IlyaOrlov/PythonCourse pull request #311
Opened 2020-10-13 15:58 UTC by TwinSss

2020-10-13 21:32 UTC, IlyaOrlov requested changes

2020-10-13 21:32 UTC, IlyaOrlov commented on Practice/SNazarov/task_9_1.py
> +          for proc in lst_pro:
Из-за того, что у вас цикл в цикле, join будет вызываться для каждого только что стартовавшего процесса. Т.е. вместо того, чтоб запустить все потоки и ждать потом завершения каждого, мы здесь запустим один поток и ждем его завершения, запустим другой - и снова ждем завершения...

2020-10-13 21:32 UTC, IlyaOrlov commented on Practice/SNazarov/task_9_1.py
> +     print(f'Running time in {round(time.perf_counter() - start_t1, 3)} seconds')
Несправедливо! time.perf_counter() - start_t1 включает в себя как время последовательного выполнения, так и время работы потоков, и время работы процессов. time.perf_counter() - start_t2 включает в себя время работы и потоков, и процессов.

2020-10-13 21:32 UTC, IlyaOrlov commented on Practice/SNazarov/task_9_2.py
> +        proc = Process(target=sum_data, args=(i, q))
Вопрос на понимание: чем обусловлен выбор процессов (а не потоков) в данной задаче?

2020-10-14 10:30 UTC, TwinSss commented on Practice/SNazarov/task_9_1.py
> +          for proc in lst_pro:
Да, поправил, что-то сдвинулось.

2020-10-14 10:30 UTC, TwinSss commented on Practice/SNazarov/task_9_1.py
> +     print(f'Running time in {round(time.perf_counter() - start_t1, 3)} seconds')
Исправил, когда смотрел как работают процессы с потоками по времени не поправил обратно.

2020-10-14 10:30 UTC, TwinSss commented on Practice/SNazarov/task_9_2.py
> +        proc = Process(target=sum_data, args=(i, q))
Из-за достаточного количества вычислений  в функции, процессы выполнят вычисление быстрее за счет использования параллелизма, а потоки за счет GIL  не могут использовать, т.к. GIL не позволяет реализовать параллельное выполнение задач, а только последовательное.(Конкурентное).

2020-10-14 16:05 UTC, IlyaOrlov commented on Practice/SNazarov/task_9_2.py
> +        proc = Process(target=sum_data, args=(i, q))
ОК. Правда, всегда нужно учитывать сложность самой вычислительной задачи. На создание процесса тоже затрачивается время. И если время последовательного вычисления сравнимо со временем создания процесса, то применять процессы (а скорее всего, и распараллеливание вообще) будет невыгодно - как стрелять из пушки по воробьям.

2020-10-14 16:05 UTC, IlyaOrlov approved these changes

2020-10-14 16:05 UTC, merged