Lection 10, Task 1,2,3
IlyaOrlov/PythonCourse pull request #313
Opened 2020-10-15 13:47 UTC by SemKilyaev

2020-10-16 18:20 UTC, IlyaOrlov requested changes

2020-10-16 18:20 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_10_Task_1_Server.py
> +            a = secret.get(i)
Если вы используете get, то (в отличие от операции индексирования []) KetError никогда не будет: если такого ключа в словаре нет - вернется значение по умолчанию None.

2020-10-16 18:20 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_10_Task_1_Server.py
> +        if j == None:
Для None, True, False лучше использовать is: if j is None. Поскольку это все глобальные объекты, разницы в результате не будет, но is (и is not) выполняется быстрее, т.к. сверяет только адреса, не переходя по этим адресам к значениям.

2020-10-19 18:21 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_10_Task_1_Server.py
> +            a = secret.get(i)
Исправил

2020-10-19 18:21 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_10_Task_1_Server.py
> +        if j == None:
Исправил

2020-10-19 18:24 UTC, IlyaOrlov approved these changes

2020-10-19 18:24 UTC, merged