Lection 11 Task 1,2
IlyaOrlov/PythonCourse pull request #318
Opened 2020-10-19 18:35 UTC by SemKilyaev

2020-10-19 21:13 UTC, IlyaOrlov requested changes

2020-10-19 21:13 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_11_Task_1.py
> +        self.conn.commit()
Для select коммит не нужен.

2020-10-19 21:13 UTC, IlyaOrlov commented on Practice/Sam_Kilyaev/Lection_11_Task_1.py
> +    return os.path.isfile(name_data_base)
Если проверку isfile сделать в начале функции, то не придется пересоздавать базу в уже существующем файле. Здесь-то вроде всегда True должно быть, т.к. если б файл с БД не создался, на предыдущих шагах исключение бы какое-нибудь вылетело.

2020-10-20 12:57 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_11_Task_1.py
> +        self.conn.commit()
Исправил

2020-10-20 12:58 UTC, SemKilyaev commented on Practice/Sam_Kilyaev/Lection_11_Task_1.py
> +    return os.path.isfile(name_data_base)
Я решил перестраховаться и сделать проверку в конце, но исправил сейчас и сделал в начале, если вдруг таблица не удалится

2020-10-20 13:19 UTC, IlyaOrlov approved these changes

2020-10-20 13:19 UTC, merged