Ekaryagin
IlyaOrlov/PythonCourse pull request #322
Opened 2020-10-24 16:07 UTC by ekaryagin

2020-10-25 12:41 UTC, IlyaOrlov requested changes

2020-10-25 12:41 UTC, IlyaOrlov commented on Practice/ekaryagin/lab8.py
> +        if not str(i).isdigit():
Если ясно, что str(i) НЕ isdigit(), зачем ее еще приведением к int мучать?

2020-10-25 12:41 UTC, IlyaOrlov commented on Practice/ekaryagin/lab8.py
> +        new_string += words[word].capitalize() + " "
Так появится лишний пробел в конце. Во избежание лучше объединять список при помощи join.

2020-10-25 12:41 UTC, IlyaOrlov commented on Practice/ekaryagin/lab8.py
> +    if not os.path.exists(source):
Проверки в строках 96 и 98 делать не нужно. Те же самые исключения и так сгенерируются при открытии файлов в режимах 'r' и 'x'.

2020-10-26 16:52 UTC, ekaryagin commented on Practice/ekaryagin/lab8.py
> +        if not str(i).isdigit():
Перемудрил на проверки отрицательных чисел... исправил

2020-10-26 16:53 UTC, ekaryagin commented on Practice/ekaryagin/lab8.py
> +        new_string += words[word].capitalize() + " "
спасибо, поправил

2020-10-26 16:53 UTC, ekaryagin commented on Practice/ekaryagin/lab8.py
> +    if not os.path.exists(source):
ок, спасибо

2020-10-26 17:47 UTC, IlyaOrlov approved these changes

2020-10-26 17:47 UTC, merged