pre exam2 tasks
IlyaOrlov/PythonCourse pull request #323
Opened 2020-10-24 20:22 UTC by asintsov

2020-10-25 12:51 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        data_size = sys.getsizeof(self.data) - 17 # не нашел нигде почему 17 байт прибавляется при encode()
Какая строка была отправлена?

2020-10-25 12:54 UTC, IlyaOrlov requested changes

2020-10-25 12:54 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        self.data = self.sock.recv(1024)
Все равно вы здесь сразу забираете 1024 байта, а следовало бы делать recv как раз в next, считывая step байтов.

2020-10-25 12:54 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_tasks_1_3.py
> +    def add_fun(self, fun, *args):
Хорошо, но еще стоит предусмотреть наличие **kwargs.

2020-10-25 14:23 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        data_size = sys.getsizeof(self.data) - 17 # не нашел нигде почему 17 байт прибавляется при encode()
При любой строке. Отправлял эти: '123', 'Привет', 'ABC' , '11111111111111111111111111111111111111'

2020-10-25 14:46 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        data_size = sys.getsizeof(self.data) - 17 # не нашел нигде почему 17 байт прибавляется при encode()
Стоит перепроверить: сравнить размер данных на сервере и клиенте. Так то encode наоборот уменьшает размер строкового объекта, выбрасывая служебную информацию, и кодируя каждый символ восьмибитовым целым.

2020-10-25 14:47 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +                lst.append(bin(self.data[i])[2:])
Здесь может выбрасываться исключение IndexError: index out of range

2020-10-25 16:55 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        data_size = sys.getsizeof(self.data) - 17 # не нашел нигде почему 17 байт прибавляется при encode()
да, проверил, все верно, encode уменьшает. Какая то особенность работы sys.getsizeof(). 
print(sys.getsizeof('111')) выводит 28, хотя казалось бы должно быть 3

2020-10-25 17:19 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +                lst.append(bin(self.data[i])[2:])
Почему? Максимально возможный end_of_range равен data_size. А значит индекс последнего байта не будет превышать (data_size - 1)

2020-10-25 17:22 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        self.data = self.sock.recv(1024)
Не очень понимаю в таком случае, как должна работать передача сервер-клиент. Натолкните на мысль. Сервер тоже должен передавать сообщение побайтово? Или он должен транслировать строку в цикле.
Если в цикле, то как итератору считывать конкретный байт из всей строки

2020-10-25 17:41 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_tasks_1_3.py
> +    def add_fun(self, fun, *args):
Добавил

2020-10-25 17:46 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        self.data = self.sock.recv(1024)
Сервер передает все сразу. А клиент в next делает recv(step) и результат (если он не пустой) возвращается из next, иначе StopIteration..

2020-10-25 17:47 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        data_size = sys.getsizeof(self.data) - 17 # не нашел нигде почему 17 байт прибавляется при encode()
Это не особенность getsizeof (она-то как раз все как есть отображает). Просто любой объект в Python - это не только сами данные, но и служебная информация (типа счетчика ссылок, длины и т.д.)

2020-10-25 17:50 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +                lst.append(bin(self.data[i])[2:])
i-й элемент self.data - и i-й байт self.data - это не одно и то же.

2020-10-25 19:49 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +                lst.append(bin(self.data[i])[2:])
Переписал без range.
сложновато пока понять, почему bytes[0] это int, а bytes[:1] это bytes, и каким образом bytes представить например в бинарном формате, чтобы не писать какой то большой своей функции.

2020-10-25 19:50 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        self.data = self.sock.recv(1024)
Написал второй вариант IterClient_2

2020-10-25 19:51 UTC, asintsov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        data_size = sys.getsizeof(self.data) - 17 # не нашел нигде почему 17 байт прибавляется при encode()
Все равно не понятно, почему print(sys.getsizeof('111'.encoding())) выводит 20. Значит какая то часть служебной информации сохраняется?

2020-10-26 17:29 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        data_size = sys.getsizeof(self.data) - 17 # не нашел нигде почему 17 байт прибавляется при encode()
Именно так. bytes - это фактически массив unsigned char + тоже какая-то служебная информация.

2020-10-26 17:30 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +        self.data = self.sock.recv(1024)
Отлично. То, что надо.

2020-10-26 17:35 UTC, IlyaOrlov commented on Practice/sintsov/pre_exam_2/pre_exam_2_task_2_client.py
> +                lst.append(bin(self.data[i])[2:])
Просто индексирование и срез это разные операции и реализованы они по-разному. Срез по определению должен возвращать значение того же, типа, что и объект, к которому он применяется.
Насчет представления в бинарном формате, например, вот: https://stackoverflow.com/questions/8815592/convert-bytes-to-bits-in-python

2020-10-26 17:36 UTC, IlyaOrlov approved these changes

2020-10-26 17:36 UTC, merged