Treushnikov
IlyaOrlov/PythonCourse pull request #326
Opened 2020-10-26 09:28 UTC by MikhailTreushnikov

Lab 9 and Lab 10

2020-10-26 18:11 UTC, IlyaOrlov requested changes
И снова надо удалить .DS_Store

2020-10-26 18:11 UTC, IlyaOrlov commented on Practice/Mihail_Treushnikov/pupil.py
> +        super()
Таки надо здесь указать метод, который вызывается через super().

2020-10-27 10:11 UTC, MikhailTreushnikov commented on Practice/Mihail_Treushnikov/pupil.py
> +        super()
если я правильно понял то поправил.

2020-10-27 10:12 UTC, MikhailTreushnikov commented
удалил опять не понимаю почему он его закидывает если вроде в gitignore лежит

2020-10-27 15:39 UTC, IlyaOrlov commented
> удалил опять не понимаю почему он его закидывает если вроде в gitignore лежит

Если вы добавляете файлы командой "git add --all .", то gitignore игнорируется: https://stackoverflow.com/questions/6612630/git-add-all-except-ignoring-files-in-gitignore-file
Возможно, проблема в этом.

2020-10-27 15:40 UTC, IlyaOrlov approved these changes

2020-10-27 15:40 UTC, merged